version: '3.9'

services:
 feallesservice:
    build:
      context: .
      dockerfile: FeallesService/Dockerfile
    deploy:
      replicas: 2
    restart:
      on-failure
 webapplication:
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    ports:
      - "8000:80"  # Map port 80 of the container to port 8000 on the host
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # Set the ASP.NET Core environment to Development



 #  depends_on: 
 #        - sqldb
 #  environment:
 #   # - DATABASE_URL=sqlserver://wehba:Allordone-12@sql-server:1433/WebServices
 #   ConnectionStrings: "Server=sqldb;Database=WebService; Trusted_Connection=True;MultipleActiveResultSets=true;TrustServerCertificate=True"
 # sqldb:
 #   image: mcr.microsoft.com/mssql/server:2019-latest
 #   environment:
 #    # - SA_PASSWORD=Allordone-12
 #    - ACCEPT_EULA=Y
 #   ports:
 #      - "1433:1433"